trigger:
  branches:
    include:
      - master
      - main

variables:
  imageName: 'games-api'
  acrName: 'registryfiap.azurecr.io'
  tag: '$(Build.BuildId)'
  dockerfilePath: 'src/Games.API/Dockerfile'
  buildContext: 'src/Games.API'

stages:
- stage: Build
  displayName: 'Build and Push Docker Image'
  jobs:
  - job: Build
    displayName: 'Build and Push Image to ACR'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: self

    - task: Docker@2
      displayName: 'Login no Azure Container Registry'
      inputs:
        command: login
        containerRegistry: 'registryfiap-serviceconnection' 

    - task: Docker@2
      displayName: 'Build Docker Image'
      inputs:
        repository: '$(imageName)'
        command: build
        Dockerfile: '$(dockerfilePath)'
        buildContext: '$(buildContext)'
        tags: |
          latest
          $(tag)

    - task: Docker@2
      displayName: 'Push Docker Image'
      inputs:
        repository: '$(imageName)'
        command: push
        tags: |
          latest
          $(tag)
