apiVersion: v1
kind: ConfigMap
metadata:
  name: games-config
  namespace: fiap-cloud-games
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"
  RabbitMQ__Host: "rabbitmq-service.rabbitmq.svc.cluster.local"
  RabbitMQ__Port: "5672"
  RabbitMQ__Username: "guest"
  RabbitMQ__VirtualHost: "/"
  ExternalServices__Users: "http://users-service:8080"
  ExternalServices__Payments: "http://payments-service:8080"

